version: "3"

networks:
  faduviva:
    external: true

services:
  fadufrontend:
    build: .
    container_name: fadu-frontend
    ports:
      - 80:80
    restart: always
    networks:
      - faduviva
